[versions]
# Plugins
androidGradle = "8.4.1"
kotlin = "1.9.24"
serializationPlugin = "1.9.24"
ksp = "1.9.24-1.0.20"

# Dependencies
about = "2.5.2"
coreKtx = "1.13.1"
appCompat = "1.6.1"
material = "1.12.0"
coroutinesAndroid = "1.8.0"
activity = "1.9.0"
fragment = "1.7.1"
constraintLayout = "2.1.4"
recyclerView = "1.3.2"
expandableTextView = "v1.6.1-x"
baseRecyclerViewAdapterHelper3 = "3.0.14"
baseRecyclerViewAdapterHelper4 = "4.1.4"
refreshLayoutKernel = "2.0.5"
refreshHeaderMaterial = "2.0.5"
refreshFooterClassics = "2.0.5"
multiType = "4.3.0"
lifecycleViewModelKtx = "2.8.0"
lifecycleRuntimeKtx = "2.8.0"
lifecycleLiveDataKtx = "2.8.0"
roomRuntime = "2.6.1"
roomKtx = "2.6.1"
roomCompiler = "2.6.1"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.7.7"
preferenceKtx = "1.2.1"
workRuntime = "2.9.0"
workRuntimeKtx = "2.9.0"
startupRuntime = "1.1.1"
palette = "1.0.0"
materialPreference = "2.0.0"
stateLayout = "1.4.2"
spannableX = "1.0.4"
datetime = "0.6.0-RC.2"
serialization = "1.6.3"
gson = "2.10.1"
jsoup = "1.17.2"
retrofit = "2.11.0"
converterGson = "2.11.0"
converterSerialization = "1.0.0"
okHttp = "4.12.0"
dnsOverHttps = "4.12.0"
coil = "2.6.0"
glide = "4.16.0"
xPopup = "2.10.0"
xPopupExt = "1.0.1"
jiaoziVideoPlayer = "7.7.2.3300"
permissionX = "1.7.1"
junit = "4.13.2"
testJunit = "1.1.5"
testEspressoCore = "3.5.1"
guava = "33.2.1-android"
exoplayer = "1.3.1"
leakCanary = "2.14"
circularRevealSwitch = "0.4.6"
desugarJdkLibs = "2.0.4"

[libraries]
# Android
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }

# Jetpack
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModelKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLiveDataKtx" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }

# Parse
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

# Network
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
converter-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "converterSerialization" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "dnsOverHttps" }

# Pic
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" } # testImplementation
test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testJunit" } # androidTestImplementation
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "testEspressoCore" } # androidTestImplementation

# video
jiaozi-video-player = { group = "cn.jzvd", name = "jiaozivideoplayer", version.ref = "jiaoziVideoPlayer" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "exoplayer" }

# Other
about = { group = "com.drakeet.about", name = "about", version.ref = "about" }
expandable-textview = { group = "com.github.MZCretin", name = "ExpandableTextView", version.ref = "expandableTextView" }
base-recyclerview-adapter-helper3 = { group = "io.github.cymchad", name = "BaseRecyclerViewAdapterHelper", version.ref = "baseRecyclerViewAdapterHelper3" }
base-recyclerview-adapter-helper4 = { group = "io.github.cymchad", name = "BaseRecyclerViewAdapterHelper4", version.ref = "baseRecyclerViewAdapterHelper4" }
refresh-layout-kernel = { group = "io.github.scwang90", name = "refresh-layout-kernel", version.ref = "refreshLayoutKernel" }
refresh-header-material = { group = "io.github.scwang90", name = "refresh-header-material", version.ref = "refreshHeaderMaterial" }
refresh-footer-classics = { group = "io.github.scwang90", name = "refresh-footer-classics", version.ref = "refreshFooterClassics" }
multitype = { group = "com.drakeet.multitype", name = "multitype", version.ref = "multiType" }
material-preference = { group = "dev.rikka.rikkax.material", name = "material-preference", version.ref = "materialPreference" }
statelayout = { group = "com.github.liangjingkanji", name = "StateLayout", version.ref = "stateLayout" }
spannable-x = { group = "com.itxca.spannablex", name = "spannablex", version.ref = "spannableX" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
xpopup = { group = "com.github.li-xiaojun", name = "XPopup", version.ref = "xPopup" }
xpopup-ext = { group = "com.github.li-xiaojun", name = "XPopupExt", version.ref = "xPopupExt" }
permission-x = { group = "com.guolindev.permissionx", name = "permissionx", version.ref = "permissionX" }
circular-reveal-switch = { group = "com.github.YenalyLiew", name = "CircularRevealSwitch", version.ref = "circularRevealSwitch" }
leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" } # debugImplementation
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" } # coreLibraryDesugaring

[bundles]

android-base = [
    "core-ktx",
    "appcompat",
    "material",
    "coroutines-android",
    "constraintlayout",
    "recyclerview"
]

android-jetpack = [
    "lifecycle-viewmodel-ktx", "lifecycle-runtime-ktx", "lifecycle-livedata-ktx",
    "activity", "activity-ktx", "fragment", "fragment-ktx",
    "room-runtime", "room-ktx",
    "navigation-fragment-ktx", "navigation-ui-ktx",
    "preference-ktx",
    "work-runtime", "work-runtime-ktx", "guava"
]

[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradle" }
com-android-library = { id = "com.android.library", version.ref = "androidGradle" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin" }